// packages/solid-js/src/server.ts
import type { JSX } from 'solid-js'
import type { CreateStreamableServerHeadOptions, Unhead } from 'unhead/types'
import { useContext } from 'solid-js'
import { createStreamableHead as _createStreamableHead, renderSSRHeadSuspenseChunkSync, STREAM_MARKER } from 'unhead/stream/server'
import { UnheadContext } from './context'

export { UnheadContext } from './context'

export { createHead, extractUnheadInputFromHtml, renderSSRHead, transformHtmlTemplate } from 'unhead/server'

// Experimental streaming support
export {
  renderSSRHeadClosing,
  renderSSRHeadShell,
  renderSSRHeadSuspenseChunk,
  streamWithHead,
} from 'unhead/stream/server'

export function createStreamableHead(options: CreateStreamableServerHeadOptions = {}): Unhead {
  return _createStreamableHead(options)
}

function useHeadStreamScript(): string {
  const head = useContext(UnheadContext)
  if (!head)
    return ''

  const update = renderSSRHeadSuspenseChunkSync(head)
  return update || STREAM_MARKER
}

/**
 * Streaming head component for Solid.
 * Place inside Suspense boundaries after async components that use useHead.
 *
 * @example
 * ```tsx
 * <Suspense fallback={<Loading />}>
 *   <AsyncPage />
 *   <HeadStream />
 * </Suspense>
 * ```
 */
export function HeadStream(): JSX.Element | null {
  const content = useHeadStreamScript()
  if (!content)
    return null

  // Use solid's escape hatch for raw HTML
  return { t: `<script>${content}</script>` } as unknown as JSX.Element
}

export type {
  CreateServerHeadOptions,
  CreateStreamableServerHeadOptions,
  SSRHeadPayload,
  Unhead,
} from 'unhead/types'

// packages/react/src/stream/server.ts
import type { ReactNode, SuspenseProps } from 'react'
import type { CreateStreamableServerHeadOptions, Unhead } from 'unhead/types'
import { createElement, Suspense, useContext } from 'react'
import { createStreamableHead as _createStreamableHead, renderSSRHeadSuspenseChunkSync, STREAM_MARKER } from 'unhead/stream/server'
import { UnheadContext } from '../context'

export * from '../server'

export function createStreamableHead(options: CreateStreamableServerHeadOptions = {}): Unhead {
  return _createStreamableHead(options)
}

export function UnheadProvider({ children, value }: { children?: ReactNode, value: Unhead }) {
  return createElement(UnheadContext.Provider, { value }, children)
}

/**
 * Streaming head component for React.
 * Place inside Suspense boundaries after async components that use useHead.
 */
export function HeadStream(): ReactNode {
  const head = useContext(UnheadContext)
  if (!head)
    return null

  const update = renderSSRHeadSuspenseChunkSync(head)

  if (update)
    return createElement('script', { dangerouslySetInnerHTML: { __html: update } })

  return createElement('script', { dangerouslySetInnerHTML: { __html: STREAM_MARKER } })
}

// Alias for streaming mode vite transform
export { HeadStream as HeadStreamScript }

/**
 * Drop-in replacement for React's Suspense that automatically includes HeadStream.
 */
export function SuspenseWithHead({ children, ...props }: SuspenseProps): ReactNode {
  return createElement(
    Suspense,
    props,
    children,
    createElement(HeadStream),
  )
}

export {
  renderSSRHeadClosing,
  renderSSRHeadShell,
  renderSSRHeadSuspenseChunk,
  streamWithHead,
} from 'unhead/stream/server'

export type {
  CreateStreamableServerHeadOptions,
  Unhead,
} from 'unhead/types'
