// packages/react/src/utils.ts
import { isValidElement } from 'react'

function resolveUnref(r: any) {
  return typeof r === 'function' ? r() : (r && 'current' in r ? r.current : r)
}

export function resolveUnrefHeadInput(ref: any): any {
  // allow promises to bubble through
  if (typeof ref === 'string' || ref instanceof Promise || ref instanceof Date || ref instanceof RegExp)
    return ref

  const root = resolveUnref(ref)
  if (!ref || !root)
    return root

  if (Array.isArray(root))
    return root.map(r => resolveUnrefHeadInput(r))

  if (typeof root === 'object' && !isValidElement(root)) {
    const resolved: Record<string, string> = {}

    for (const k in root) {
      if (!Object.prototype.hasOwnProperty.call(root, k)) {
        continue
      }

      if (k === 'titleTemplate' || (k[0] === 'o' && k[1] === 'n')) {
        resolved[k] = resolveUnref(root[k])
        continue
      }

      resolved[k] = resolveUnrefHeadInput(root[k])
    }

    return resolved
  }

  return root
}

// packages/angular/src/unhead/utils.ts
import { isSignal, untracked } from '@angular/core'

function resolveSignal(r: any) {
  return typeof r === 'function' ? r() : isSignal(r) ? r() : r
}

export function resolveSignalHeadInput(signal: any): any {
  if (signal instanceof Promise || signal instanceof Date || signal instanceof RegExp)
    return signal

  const root = resolveSignal(signal)
  if (!signal || !root)
    return root

  if (Array.isArray(root))
    return root.map(r => resolveSignalHeadInput(r))

  if (typeof root === 'object') {
    const resolved: Record<string, any> = {}

    for (const k in root) {
      if (!Object.prototype.hasOwnProperty.call(root, k)) {
        continue
      }

      if (k === 'titleTemplate' || (k[0] === 'o' && k[1] === 'n')) {
        resolved[k] = isSignal(root[k]) ? untracked(() => root[k]()) : root[k]
        continue
      }

      resolved[k] = resolveSignalHeadInput(root[k])
    }

    return resolved
  }

  return root
}
