// examples/vite-ssr-react-streaming-ts/src/components/SlowComponent.tsx
import { useState, useEffect } from 'react'
import { Head } from '@unhead/react'

// Artificial delay function to simulate slow loading data
const createResource = () => {
  return new Promise<string>((resolve) => {
    // Simulate a network request that takes 1.5 seconds
    setTimeout(() => {
      resolve('Data loaded from first slow component!')
    }, 1500)
  })
}

async function SlowComponent() {
  const [data, setData] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    let isMounted = true

    // Load data with artificial delay
    createResource().then((result) => {
      if (isMounted) {
        setData(result)
        setLoading(false)
      }
    })

    return () => {
      isMounted = false
    }
  }, [])

  if (loading) {
    return <div>Loading data...</div>
  }

  return (
    <div className="slow-component first">
      <h3>First Slow Component</h3>
      <p>This component took 1.5 seconds to load.</p>
      <p>Data: {data}</p>
      <p>Notice how this component appeared before the others.</p>
      <Head>
        <title>First Slow Component</title>
        <meta name="description" content="This is the first slow component." />
        <link rel="stylesheet" href="/styles/slow-component.css" />
      </Head>
    </div>
  )
}

export default SlowComponent

// examples/vite-ssr-vue-streaming/src/components/SlowComponent.vue
<script setup>
import { ref } from 'vue'
import SlowComponentTwo from './SlowComponentTwo.vue'

const message = ref('')

// Simulate slow component load
await new Promise(resolve => setTimeout(resolve, 3000))
message.value = 'Component loaded after 3 second delay!'

useHead({
  title: 'S1',
  style: [
    '.slow-component { color: red; }',
  ],
  link: [
    {
      key: 'preload',
      rel: 'stylesheet',
      href: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta1/css/all.min.css',
    },
  ],
  meta: [
    {
      name: 'description',
      content: 'This is a slow component',
    },
  ]
})
</script>

<template>
  <div class="slow-component">
    <p>Slow component one</p>
    <SlowComponentTwo />
  </div>
</template>

<style>
.slow-component {
  padding: 2rem;
  margin: 1rem 0;
  background-color: #f9f9f9;
  border-radius: 8px;
  border: 1px solid #ddd;
}
</style>
