// examples/template-ssr-react-ts/src/entry-server.tsx
import { StrictMode } from 'react'
import { renderToString } from 'react-dom/server'
import App from './App'
import { createHead, UnheadProvider } from '@unhead/react/server'

export function render(_url: string) {
  const head = createHead()
  const html = renderToString(
    <StrictMode>
      <UnheadProvider value={head}>
      <App />
      </UnheadProvider>
    </StrictMode>,
  )
  return { html, head }
}

// examples/vite-ssr-solid/src/entry-server.tsx
import { renderToString } from 'solid-js/web'
import App from './App'
import { createHead, UnheadContext } from '@unhead/solid-js/server'

export function render(_url: string) {
  const unhead = createHead({
    // change default initial lang
    init: [
      {
        htmlAttrs: { lang: 'en' },
        title: 'Default title',
        titleTemplate: '%s - My Site',
      },
    ]
  })
  const html = renderToString(() => <UnheadContext.Provider value={unhead}><App /></UnheadContext.Provider>)
  return { html, unhead }
}
