// examples/vite-ssr-react-streaming/src/entry-client.tsx
import './index.css'
import { StrictMode } from 'react'
import { hydrateRoot } from 'react-dom/client'
import App from './App'
import { UnheadProvider, createHead } from '@unhead/react/client'

const head = createHead({ /* config */ })

hydrateRoot(
  document.getElementById('root') as HTMLElement,
  <StrictMode>
    <UnheadProvider head={head}>
    <App />
    </UnheadProvider>
  </StrictMode>,
)

// examples/vite-ssr-solid/src/entry-client.tsx
/* @refresh reload */
import './index.css'
import { hydrate } from 'solid-js/web'
import App from './App'
import { createHead } from 'unhead/client'
import { createContext, useContext } from 'solid-js';

hydrate(() => {
  const head = createHead()
  const context = createContext({ head })
  return <App />
}, document.getElementById('root'))
