// examples/vite-ssr-react-ts/src/entry-client.tsx
import './index.css'
import { StrictMode } from 'react'
import { hydrateRoot } from 'react-dom/client'
import App from './App'
import { UnheadProvider, createHead } from '@unhead/react/client'

const head = createHead({ /* config */ })

hydrateRoot(
  document.getElementById('root') as HTMLElement,
  <StrictMode>
    <UnheadProvider value={head}>
      <App />
    </UnheadProvider>
  </StrictMode>,
)

// examples/vite-ssr-solid/src/entry-client.tsx
/* @refresh reload */
import './index.css'
import { hydrate } from 'solid-js/web'
import App from './App'
import { createHead, UnheadContext } from '@unhead/solid-js/client'

hydrate(() => {
  const head = createHead()
  return (<UnheadContext.Provider value={head}><App /></UnheadContext.Provider>)
}, document.getElementById('root'))
