// packages/solid-js/src/precompiled/client-csr.ts
import type { PrecompiledClientInput } from 'unhead/precompiled/client'
import type { PrecompiledCsrClientHead } from 'unhead/precompiled/client-csr'
import type { ResolvableHead, UseSeoMetaInput } from 'unhead/types'
import { onCleanup } from 'solid-js'

export type { PrecompiledClientEntry, PrecompiledClientInput, PrecompiledClientTag } from 'unhead/precompiled/client'
export { createHead, renderDOMHead } from 'unhead/precompiled/client-csr'
export type { PrecompiledCsrClientHead } from 'unhead/precompiled/client-csr'

/** Mount one build-finalized SPA-only client plan for the current Solid owner. @experimental */
export function useHead(input: ResolvableHead, options: { bindings?: readonly (() => unknown)[], head: PrecompiledCsrClientHead }): void {
  const entry = options.head.push(input as unknown as PrecompiledClientInput)
  onCleanup(entry.dispose)
}

/** Mount one build-finalized SPA-only SEO plan for the current Solid owner. @experimental */
export const useSeoMeta = useHead as (input: UseSeoMetaInput, options: { bindings?: readonly (() => unknown)[], head: PrecompiledCsrClientHead }) => void

// packages/react/src/precompiled/client-csr.ts
import type { ReactNode } from 'react'
import type { PrecompiledClientInput } from 'unhead/precompiled/client'
import type { PrecompiledCsrClientHead } from 'unhead/precompiled/client-csr'
import type { UseHeadInput, UseSeoMetaInput } from 'unhead/types'
import { createContext, createElement, useContext, useEffect, useRef } from 'react'
import { createHead as createCoreHead } from 'unhead/precompiled/client-csr'

export { renderDOMHead } from 'unhead/precompiled/client-csr'

export const UnheadContext = /* @__PURE__ */ createContext<PrecompiledCsrClientHead | null>(null)

export interface PrecompiledReactCsrEntryOptions {
  bindings?: readonly (() => unknown)[]
  head?: PrecompiledCsrClientHead
}

/** Create a SPA-only React client head that never scans or adopts initial DOM nodes. */
/* @__NO_SIDE_EFFECTS__ */
export function createHead(): PrecompiledCsrClientHead {
  return createCoreHead()
}

export function useUnhead(): PrecompiledCsrClientHead {
  const head = useContext(UnheadContext)
  if (!head || !('push' in head))
    throw new Error('useHead() was called without a precompiled React CSR provider.')
  return head
}

/** Register a build-finalized SPA plan after commit and dispose it with the React owner. */
export function useHead(input: UseHeadInput, options: PrecompiledReactCsrEntryOptions = {}): void {
  const context = useContext(UnheadContext)
  const head = options.head || (context && 'push' in context ? context : undefined)
  if (!head)
    throw new Error('useHead() was called without a precompiled React CSR provider.')
  const plan = input as unknown as PrecompiledClientInput
  useEffect(() => {
    const entry = head.push(plan, options.bindings)
    return entry.dispose
  }, [head, plan])
}

export const useSeoMeta = useHead as (
  input: UseSeoMetaInput,
  options?: PrecompiledReactCsrEntryOptions,
) => void

export interface UnheadProviderProps {
  children: ReactNode
  head?: PrecompiledCsrClientHead
  value?: PrecompiledCsrClientHead
}

export function UnheadProvider({ children, head, value }: UnheadProviderProps) {
  const headRef = useRef<PrecompiledCsrClientHead | null>(null)
  if (!head && !value && !headRef.current)
    headRef.current = createHead()
  return createElement(UnheadContext.Provider, { value: head || value || headRef.current }, children)
}

export type {
  PrecompiledClientInput,
  PrecompiledCsrClientHead,
}
