// packages/react/src/types/util.ts
import type { Falsey } from '@unhead/schema'
import type { RefObject } from 'react'

export type MaybeComputedRef<T> = T | (() => T) | RefObject<T>

export type ResolvableArray<T> = MaybeComputedRef<MaybeComputedRef<T>[]>

export type ResolvableProperties<T> = {
  [key in keyof T]?: MaybeComputedRef<T[key] | Falsey>
}

// packages/angular/src/unhead/types/util.ts
import type { Signal, WritableSignal } from '@angular/core'
import type { Falsey } from '@unhead/schema'

export type MaybeSignal<T> = T | (() => T) | Signal<T> | WritableSignal<T>

export type ResolvableArray<T> = MaybeSignal<MaybeSignal<T>[]>

export type ResolvableProperties<T> = {
  [key in keyof T]?: MaybeSignal<T[key] | Falsey>
}
