// examples/vite-ssr-vue-streaming/src/pages/HomePage.vue
<script setup lang="ts">
import { Suspense } from 'vue'
import { useHead } from '@unhead/vue'
import { RouterLink } from 'vue-router'
import Header from '../components/Header.vue'
import Sidebar from '../components/Sidebar.vue'
import HeroBanner from '../components/HeroBanner.vue'
import ProductCard from '../components/ProductCard.vue'
import Reviews from '../components/Reviews.vue'
import Newsletter from '../components/Newsletter.vue'

useHead({
  title: 'StreamShop - Vue Streaming SSR Demo',
  htmlAttrs: { lang: 'en' },
  meta: [
    { charset: 'utf-8' },
    { name: 'viewport', content: 'width=device-width, initial-scale=1' },
    { name: 'description', content: 'E-commerce demo with streaming SSR' },
    { name: 'page-id', content: 'home' },
  ],
  link: [{ rel: 'canonical', href: 'https://example.com/' }],
})
</script>

<template>
  <div class="app">
    <div class="stream-progress" />
    <Suspense>
      <template #default>
        <Header />
      </template>
      <template #fallback>
        <div class="skeleton header-skeleton">Loading header...</div>
      </template>
    </Suspense>

    <div class="main-layout">
      <Suspense>
        <template #default>
          <Sidebar />
        </template>
        <template #fallback>
          <div class="skeleton sidebar-skeleton">Loading categories...</div>
        </template>
      </Suspense>

      <main class="content">
        <nav class="page-nav">
          <RouterLink to="/" class="nav-link active">Home</RouterLink>
          <RouterLink to="/about" class="nav-link">About</RouterLink>
        </nav>

        <Suspense>
          <template #default>
            <HeroBanner />
          </template>
          <template #fallback>
            <div class="skeleton hero-skeleton">Loading banner...</div>
          </template>
        </Suspense>

        <section class="products-section">
          <h2>Featured Products</h2>
          <div class="product-grid">
            <Suspense>
              <template #default>
                <ProductCard :id="1" :delay="1375" />
              </template>
              <template #fallback>
                <div class="skeleton product-skeleton">Loading...</div>
              </template>
            </Suspense>
            <Suspense>
              <template #default>
                <ProductCard :id="2" :delay="1500" />
              </template>
              <template #fallback>
                <div class="skeleton product-skeleton">Loading...</div>
              </template>
            </Suspense>
            <Suspense>
              <template #default>
                <ProductCard :id="3" :delay="1625" />
              </template>
              <template #fallback>
                <div class="skeleton product-skeleton">Loading...</div>
              </template>
            </Suspense>
            <Suspense>
              <template #default>
                <ProductCard :id="4" :delay="1750" />
              </template>
              <template #fallback>
                <div class="skeleton product-skeleton">Loading...</div>
              </template>
            </Suspense>
            <Suspense>
              <template #default>
                <ProductCard :id="5" :delay="1875" />
              </template>
              <template #fallback>
                <div class="skeleton product-skeleton">Loading...</div>
              </template>
            </Suspense>
            <Suspense>
              <template #default>
                <ProductCard :id="6" :delay="2000" />
              </template>
              <template #fallback>
                <div class="skeleton product-skeleton">Loading...</div>
              </template>
            </Suspense>
          </div>
        </section>

        <Suspense>
          <template #default>
            <Reviews />
          </template>
          <template #fallback>
            <div class="skeleton reviews-skeleton">Loading reviews...</div>
          </template>
        </Suspense>

        <Suspense>
          <template #default>
            <Newsletter />
          </template>
          <template #fallback>
            <div class="skeleton newsletter-skeleton">Loading newsletter...</div>
          </template>
        </Suspense>
      </main>
    </div>

    <footer class="site-footer">
      <p>StreamShop, Vue Streaming SSR Demo</p>
    </footer>
  </div>
</template>

// examples/vite-ssr-react-streaming/src/pages/HomePage.tsx
import { Suspense } from 'react'
import { useHead } from '@unhead/react'
import { Link } from 'react-router-dom'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'
import HeroBanner from '../components/HeroBanner'
import ProductCard from '../components/ProductCard'
import Reviews from '../components/Reviews'
import Newsletter from '../components/Newsletter'

export default function HomePage() {
  useHead({
    title: 'StreamShop - React Streaming SSR Demo',
    htmlAttrs: { lang: 'en' },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'description', content: 'E-commerce demo with streaming SSR' },
      { name: 'page-id', content: 'home' },
    ],
    link: [{ rel: 'canonical', href: 'https://example.com/' }],
  })

  return (
    <div className="app">
      <div className="stream-progress" />
      <Suspense fallback={<div className="skeleton header-skeleton">Loading header...</div>}>
        <Header />
      </Suspense>

      <div className="main-layout">
        <Suspense fallback={<div className="skeleton sidebar-skeleton">Loading categories...</div>}>
          <Sidebar />
        </Suspense>

        <main className="content">
          <nav className="page-nav">
            <Link to="/" className="nav-link active">Home</Link>
            <Link to="/about" className="nav-link">About</Link>
          </nav>

          <Suspense fallback={<div className="skeleton hero-skeleton">Loading banner...</div>}>
            <HeroBanner />
          </Suspense>

          <section className="products-section">
            <h2>Featured Products</h2>
            <div className="product-grid">
              <Suspense fallback={<div className="skeleton product-skeleton">Loading...</div>}>
                <ProductCard id={1} delay={1375} />
              </Suspense>
              <Suspense fallback={<div className="skeleton product-skeleton">Loading...</div>}>
                <ProductCard id={2} delay={1500} />
              </Suspense>
              <Suspense fallback={<div className="skeleton product-skeleton">Loading...</div>}>
                <ProductCard id={3} delay={1625} />
              </Suspense>
              <Suspense fallback={<div className="skeleton product-skeleton">Loading...</div>}>
                <ProductCard id={4} delay={1750} />
              </Suspense>
              <Suspense fallback={<div className="skeleton product-skeleton">Loading...</div>}>
                <ProductCard id={5} delay={1875} />
              </Suspense>
              <Suspense fallback={<div className="skeleton product-skeleton">Loading...</div>}>
                <ProductCard id={6} delay={2000} />
              </Suspense>
            </div>
          </section>

          <Suspense fallback={<div className="skeleton reviews-skeleton">Loading reviews...</div>}>
            <Reviews />
          </Suspense>

          <Suspense fallback={<div className="skeleton newsletter-skeleton">Loading newsletter...</div>}>
            <Newsletter />
          </Suspense>
        </main>
      </div>

      <footer className="site-footer">
        <p>© 2024 StreamShop - React Streaming SSR Demo</p>
      </footer>
    </div>
  )
}
