// examples/vite-ssr-solidjs-streaming/src/components/HeroBanner.tsx
import { createResource } from 'solid-js'
import { useHead } from '@unhead/solid-js'

const DATA = { title: 'Summer Sale!', subtitle: 'Up to 50% off selected items', code: 'SUMMER50' }

const fetchData = async () => {
  await new Promise(r => setTimeout(r, 1000))
  return DATA
}

export default function HeroBanner() {
  const [promo] = createResource(fetchData)

  useHead({
    title: 'StreamShop 3/11 - Loading...',
    meta: [{ name: 'promo-code', content: promo()?.code || '' }],
    style: [{ key: 'progress', innerHTML: '.stream-progress::after{width:27%}' }],
  })

  return (
    <div class="hero-banner">
      <h1>{promo()?.title}</h1>
      <p>{promo()?.subtitle}</p>
      <button class="cta-button">Use code: {promo()?.code}</button>
    </div>
  )
}

// examples/vite-ssr-svelte-streaming/src/components/HeroBanner.svelte
<script lang="ts">
import { useHead } from '@unhead/svelte'

const DATA = { title: 'Winter Sale', subtitle: 'Up to 50% off selected items', discount: 50 }

const fetchData = async () => {
  await new Promise(r => setTimeout(r, 750))
  return DATA
}

const data = await fetchData()

useHead({
  title: 'StreamShop 3/11 - Loading...',
  meta: [
    { property: 'og:title', content: `${data.title} - ${data.discount}% Off` },
  ],
  style: [{ key: 'progress', innerHTML: '.stream-progress::after{width:27%}' }],
})
</script>

<svelte:boundary>
  <div class="hero-banner">
    <h1>{data.title}</h1>
    <p>{data.subtitle}</p>
    <button class="cta-button">Shop Now</button>
  </div>
  {#snippet pending()}
    <div class="hero-banner skeleton hero-skeleton">Loading banner...</div>
  {/snippet}
</svelte:boundary>
