// examples/vite-ssr-svelte-streaming/src/App.svelte
<script lang="ts">
import svelteLogo from './assets/svelte.svg'
import Counter from './lib/Counter.svelte'
import SlowComponent from './lib/SlowComponent.svelte'
import { useHead } from '@unhead/svelte'

useHead({
  htmlAttrs: { class: 'layout-default' },
  bodyAttrs: { style: 'overflow: hidden;' },
  script: [
    {
      tagPosition: 'bodyClose',
      innerHTML: 'console.log("Hello world")',
    },
  ],
})
</script>

<main>
  <div>
    <a href="https://vite.dev" target="_blank" rel="noreferrer">
      <img src="/vite.svg" class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vite + Svelte Streaming</h1>

  <div class="card">
    <Counter />
  </div>

  <div>
    <SlowComponent data={{ message: 'Data from parent' }} />
  </div>

  <p class="read-the-docs">
    Click on the Vite and Svelte logos to learn more
  </p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>

// examples/vite-ssr-vue-streaming/src/App.vue
<script setup>
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import HelloWorld from './components/HelloWorld.vue'
import SlowComponent from './components/SlowComponent.vue'
import { useHead } from '@unhead/vue'

useHead({
  htmlAttrs: {
    class: 'layout-default',
  },
  bodyAttrs: {
    style: 'overflow: hidden;',
  },
  title: 'hello world',
  script: [
    {
      tagPosition: 'bodyClose',
      innerHTML: 'console.log("Hello world")',
    }
  ]
})
</script>

<template>
<div>
  <div>
    <a href="https://vite.dev" target="_blank">
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
  <div>
    <Suspense>
      <template #default>
      <SlowComponent />
      </template>
      <template #fallback>
      <div class="loading">Loading slow component...</div>
      </template>
    </Suspense>
  </div>
</div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
.loading {
  padding: 2rem;
  margin: 1rem 0;
  background-color: #fafafa;
  border-radius: 8px;
  border: 1px dashed #ddd;
  font-style: italic;
}
</style>
