// examples/vite-ssr-vue-streaming/src/components/HeroBanner.vue
<script setup lang="ts">
import { useHead } from '@unhead/vue'

const delay = typeof window === 'undefined' ? 1000 : 0
const data = await new Promise<{ title: string; subtitle: string; discount: number }>(resolve =>
  setTimeout(() => resolve({
    title: 'Winter Sale',
    subtitle: 'Up to 50% off selected items',
    discount: 50
  }), delay)
)

useHead({
  title: 'StreamShop 3/11 - Loading...',
  meta: [
    { property: 'og:title', content: `${data.title} - ${data.discount}% Off` },
  ],
  style: [{ key: 'progress', innerHTML: '.stream-progress::after{width:27%}' }],
})
</script>

<template>
  <component :is="'script'" v-html="`window.__streamLog?.('Hero Banner', '#f472b6')`" />
  <div class="hero-banner">
    <h1>{{ data.title }}</h1>
    <p>{{ data.subtitle }}</p>
    <button class="cta-button">Shop Now</button>
  </div>
</template>

// examples/vite-ssr-react-streaming/src/components/HeroBanner.tsx
import { use } from 'react'
import { useHead } from '@unhead/react'

const cache = new Map<string, Promise<{ title: string; subtitle: string; discount: number }>>()

export default function HeroBanner() {
  const cacheKey = 'hero'
  if (!cache.has(cacheKey)) {
    const delay = typeof window === 'undefined' ? 1000 : 0
    cache.set(cacheKey, new Promise(resolve =>
      setTimeout(() => resolve({
        title: 'Winter Sale',
        subtitle: 'Up to 50% off selected items',
        discount: 50
      }), delay)
    ))
    cache.get(cacheKey)!.finally(() => setTimeout(() => cache.delete(cacheKey), 100))
  }
  const data = use(cache.get(cacheKey)!)

  useHead({
    title: 'StreamShop 3/11 - Loading...',
    meta: [
      { property: 'og:title', content: `${data.title} - ${data.discount}% Off` },
    ],
    style: [{ key: 'progress', innerHTML: '.stream-progress::after{width:27%}' }],
  })

  return (
    <>
    <script dangerouslySetInnerHTML={{ __html: `window.__streamLog?.('🎯 Hero Banner', '#f472b6')` }} />
    <div className="hero-banner">
      <h1>{data.title}</h1>
      <p>{data.subtitle}</p>
      <button className="cta-button">Shop Now →</button>
    </div>
    </>
  )
}
