// examples/vite-ssr-solidjs-streaming/src/entry-client.tsx
import { hydrate } from 'solid-js/web'
import { createStreamableHead, UnheadContext } from '@unhead/solid-js/stream/client'
import App from './App'

const head = createStreamableHead()

hydrate(
  () => (
    <UnheadContext.Provider value={head}>
      <App url={window.location.pathname} />
    </UnheadContext.Provider>
  ),
  document.getElementById('app')!
)

// examples/vite-ssr-react-streaming/src/entry-client.tsx
import { hydrateRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import { UnheadProvider, createStreamableHead } from '@unhead/react/stream/client'
import App from './App'

const head = createStreamableHead()

hydrateRoot(
  document.getElementById('app')!,
  <UnheadProvider value={head}>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </UnheadProvider>
)
